### ISSUE TITLE
Web Browser problem

### ISSUE THREAD

**Issue by photopea** [image-js/png-js#4]
Hi, can you make it work in a web browser?
I am getting a following error: 
PNGDecoder.js:3 Uncaught ReferenceError: require is not defined

**Comment by targos** [comment]
Hello, the library cannot run in the browser directly from the source.
You can either use a module bundler like [browserify](http://browserify.org/) or [webpack](https://webpack.github.io/) in your project or load it directly from a [browserify CDN](https://wzrd.in/standalone/fast-png@latest)

**Comment by photopea** [comment]
By the way, can you test, if your decoder can correctly decode this file? 
![pea](https://cloud.githubusercontent.com/assets/15955558/15387366/0e33294c-1dad-11e6-8c5b-db4365c6b77f.png)

**Comment by targos** [comment]
No, sorry. I haven't had time to add support for palette-based images.

**Comment by targos** [comment]
@photopea I added basic support for palettes in v1.1.0.
The decoded image will have two properties:
* `image.palette`: an array of arrays. Each element contains the RGB values
* `image.data` an array of color indexes referring to the palette array

**Comment by photopea** [comment]
this library has 10 kB, but Browserify CDN asks me to download 228 kB file.

We are developing an online editor www.Photopea.com and we would like to decode PNGs at the client side. Removing Node.js dependencies from your code must be easy and it will let it run on billions of devices.

If your library was written in C++ and you asked me to compile it to JS, it makes sense. But you wrote it in JS and you are asking me to compile your JS to a standard JS through additional software, which is crazy.

**Comment by photopea** [comment]
BTW. I decided to make my own PNG parser.  Unlike your library, it fully supports PNG format, including all color depths and interlacing.  https://github.com/photopea/UPNG.js  . 

BTW. why do you develop these parsers? Do you use them in any specific product?
